version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  build-and-test:
    docker:
      # replace with your preferred image
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - node/install-yarn
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build
      - run: yarn e2e:headless
workflows:
  example-workflow:
    jobs:
      - build-and-test