version: 2.1
jobs:
  e2e:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - run: node --version
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          yarn build
          yarn e2e:headless

workflows:
  test:
    jobs:
      - e2e
