version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install-yarn
      - node/install-packages
      - run: yarn build
      - run: yarn e2e:headless
workflows:
  example-workflow:
    jobs:
      - example-job