name: Cypress Tests

on:
  push:
    branches-ignore:
      - "renovate/**"

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome88-ff89
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
      # report machine parameters
      - run: node -p 'os.cpus()'
      - run: yarn build

      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: .next
  test:
    runs-on: ubuntu-latest
    needs: install
    container: cypress/browsers:node14.17.0-chrome88-ff89
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
    steps:
        - name: "UI Tests - Chrome"
          uses: cypress-io/github-action@v2
          with:
            start: yarn start:ci
            wait-on: "http://localhost:3000"
            wait-on-timeout: 120
            browser: chrome
            record: true
            parallel: true
            group: "UI - Chrome"
            spec: cypress/integration/*
          env:
            CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
